### ISSUE TITLE
Missing makefile/build instructions

### ISSUE THREAD

**Issue by breedx2** [jstorts/Twin-Peaks-Game#3]
It would be awesome if somebody wanting to try this out could just clone the repo and build it, but there is no makefile and/or build instructions.

**Comment by jstorts** [comment]
I should add that. I developed this in Visual Studio so I was using the build tools there. It was also deployed and tested on one of OSU's linux servers, and I do have a makefile from that. I'll find that and push it later today.

**Comment by jstorts** [comment]
I added a makefile and some build instructions. The instruction for playing the game are pretty straightforward and the menu includes a script that gives you the solution if you want to see how it ends.
